# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administrador_marcadores.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgAdmMarcadores(object):
    def setupUi(self, dlgAdmMarcadores):
        dlgAdmMarcadores.setObjectName("dlgAdmMarcadores")
        dlgAdmMarcadores.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgAdmMarcadores)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(dlgAdmMarcadores)
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget.setDragEnabled(False)
        self.listWidget.setDragDropOverwriteMode(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.label = QtWidgets.QLabel(dlgAdmMarcadores)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(dlgAdmMarcadores)
        QtCore.QMetaObject.connectSlotsByName(dlgAdmMarcadores)

    def retranslateUi(self, dlgAdmMarcadores):
        _translate = QtCore.QCoreApplication.translate
        dlgAdmMarcadores.setWindowTitle(_translate("dlgAdmMarcadores", "Administrador de marcadores"))
        self.label.setText(_translate("dlgAdmMarcadores", "Arrastre los marcadores para ordenarlos a su gusto, pulse con el botón derecho para eliminar un marcador"))
