# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlgabout.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(239, 175)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgAbout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLogo = QtWidgets.QLabel(dlgAbout)
        self.lblLogo.setMinimumSize(QtCore.QSize(64, 64))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap("img/pyqtbrowser.png"))
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout.addWidget(self.lblLogo)
        self.lblNomPro = QtWidgets.QLabel(dlgAbout)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNomPro.setFont(font)
        self.lblNomPro.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNomPro.setObjectName("lblNomPro")
        self.verticalLayout.addWidget(self.lblNomPro)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblVersionPro = QtWidgets.QLabel(dlgAbout)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblVersionPro.setFont(font)
        self.lblVersionPro.setObjectName("lblVersionPro")
        self.horizontalLayout.addWidget(self.lblVersionPro)
        self.lblVersion = QtWidgets.QLabel(dlgAbout)
        self.lblVersion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVersion.setObjectName("lblVersion")
        self.horizontalLayout.addWidget(self.lblVersion)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblAutor = QtWidgets.QLabel(dlgAbout)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAutor.setFont(font)
        self.lblAutor.setObjectName("lblAutor")
        self.horizontalLayout_2.addWidget(self.lblAutor)
        self.lblNombre = QtWidgets.QLabel(dlgAbout)
        self.lblNombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNombre.setObjectName("lblNombre")
        self.horizontalLayout_2.addWidget(self.lblNombre)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgAbout)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dlgAbout)
        self.buttonBox.accepted.connect(dlgAbout.accept)
        self.buttonBox.rejected.connect(dlgAbout.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Acerca de"))
        self.lblNomPro.setText(_translate("dlgAbout", "pyQtBrowser"))
        self.lblVersionPro.setText(_translate("dlgAbout", "Versión:"))
        self.lblVersion.setText(_translate("dlgAbout", "0.0.1"))
        self.lblAutor.setText(_translate("dlgAbout", "Autor:"))
        self.lblNombre.setText(_translate("dlgAbout", "Wilhelm Najberg"))
