# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlghistorial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgHistorial(object):
    def setupUi(self, dlgHistorial):
        dlgHistorial.setObjectName("dlgHistorial")
        dlgHistorial.resize(560, 398)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgHistorial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(dlgHistorial)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 540, 347))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBorrarFecha = QtWidgets.QPushButton(dlgHistorial)
        self.btnBorrarFecha.setObjectName("btnBorrarFecha")
        self.horizontalLayout.addWidget(self.btnBorrarFecha)
        self.btnBorrarSel = QtWidgets.QPushButton(dlgHistorial)
        self.btnBorrarSel.setObjectName("btnBorrarSel")
        self.horizontalLayout.addWidget(self.btnBorrarSel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(dlgHistorial)
        QtCore.QMetaObject.connectSlotsByName(dlgHistorial)

    def retranslateUi(self, dlgHistorial):
        _translate = QtCore.QCoreApplication.translate
        dlgHistorial.setWindowTitle(_translate("dlgHistorial", "Historial"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("dlgHistorial", "Título"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("dlgHistorial", "Fecha"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("dlgHistorial", "Hora"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("dlgHistorial", "URL"))
        self.btnBorrarFecha.setText(_translate("dlgHistorial", "Borrar por fecha"))
        self.btnBorrarSel.setText(_translate("dlgHistorial", "Borrar selección"))
